# Generated by Django 4.2 on 2023-04-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
